msm8996: import doze from gzosp
https://github.com/GZOSP-Devices/device_oneplus_oneplus3/tree/9.0/doze

commit f7881910bfd5a0327d5858f3b50976b60e1bf19f
Author: Anton Hansson <hansson@google.com>
Date:   Tue Aug 14 10:19:34 2018 -0400

    Set LOCAL_SDK_VERSION where possible.

    This change sets LOCAL_SDK_VERSION for all packages where
    this is possible without breaking the build, and
    LOCAL_PRIVATE_PLATFORM_APIS := true otherwise.

    Setting one of these two will be made required soon, and this
    is a change in preparation for that. Not setting LOCAL_SDK_VERSION
    makes the app implicitly depend on the bootclasspath, which is
    often not required. This change effectively makes depending on
    private apis opt-in rather than opt-out.

    Test: make relevant packages
    Bug: 73535841

    Change-Id: Ic906adbd670c4dbfe2cdf0b71cdbeaf9ac08a27e

commit 7d158a42f43a1469f7524d7a79ba1aa6c53c8bbf
Author: Alex <alex@dirtyunicorns.com>
Date:   Sun Jul 1 08:50:02 2018 -0500

    Ensure Doze respects RTL

    - Add in a few null checks to prevent possible NPE's
    - Add missing INTERACT_ACROSS_USERS permission

    Change-Id: I4c4daf928f3298409d96309d86a333a222ad111f

commit c1b25134874f15f753d984e6df27e43d59a83964
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Thu Jun 14 09:06:27 2018 -0400

    Custom doze: use ExecutorService to handle sensor listener

    maybe this is useless, but out of curiosity let's try what Google
    did for systemui here:
    ezio84/abc_frameworks_base@fabc743

    registering a sensor seems to be an expensive operation, and we do it on each
    screen-on event, so moving it to an asynchronous task looks like
    a good idea anyway.

    The interesting part about ExecutorService api:
    By
    moving all non-essential binder calls of the main thread or to the
    next frame, we bring this down to 5ms, such that window animation
    and Keyguard animation starts about at the same time.
    https://developer.android.com/reference/java/util/concurrent/ExecutorService
    Change-Id: Id33a200b68e2f313af4258c6109c7b80aa93329c

commit c033c9a7d16d3abc29d812334cb5eba69aa37e49
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Wed May 23 05:49:58 2018 -0400

    Fix custom doze receiver protected broadcast logspam

    05-23 10:32:55.236   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system
1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
    05-23 10:32:55.236   834 13503 E ActivityManager: java.lang.Throwable
    05-23 10:32:55.236   834 13503 E ActivityManager:       at
com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at
com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19603)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
    05-23 10:32:55.236   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)
    05-23 10:32:55.243   834 13503 E ActivityManager: Sending non-protected broadcast com.android.systemui.doze.pulse from system
1639:com.custom.ambient.display/1000 pkg com.custom.ambient.display
    05-23 10:32:55.243   834 13503 E ActivityManager: java.lang.Throwable
    05-23 10:32:55.243   834 13503 E ActivityManager:       at
com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19091)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at
com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19696)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19838)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2922)
    05-23 10:32:55.243   834 13503 E ActivityManager:       at android.os.Binder.execTransact(Binder.java:697)

    Change-Id: I132298a7acf246b8153019ce5a3f4129d9eeca4b

commit 2a618964e00a58ace5f8af6408c35e08dba62071
Author: ezio84 <brabus84@gmail.com>
Date:   Thu May 17 15:34:28 2018 +0200

    Custom doze service improvements

    don't start the service when all options are disabled or just
    pulse on notification is enabled

    start the service when enabling options only if it's not already running

    Change-Id: I07dab2e38b6701669dfe07d7154716de4b781609

commit 9a220e913d5c40da18dfcb55313fd40060878c35
Author: Ezio Lacandia Bijelkic <brabus84@gmail.com>
Date:   Sat May 12 18:57:43 2018 -0400

    Allow to enable doze proximity actions without the notifications one

    Change-Id: Iacb5573c3b66d2e33c67dbf9ddbedc66b7ffaef0

commit 5adcd3eace7ca72c45cef3a632bb3acb31f48caa
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Sat Jan 6 01:21:06 2018 -0500

    Change targeted sdk up to 27

    This not only gets us inline with other packages we compile but fixes a
    weird theme issue in that the navbar was black on black, black icons on
    a black bar. We could of gone about this a different way by defining the
    theme and calling it from the manifest but this is just easier :-)

    Change-Id: I1fd191fe6991071bdfa278c704074b28c11cf1c1

commit 93e7aaab9c4df7cb087e4642806145e2c17cab6d
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Mon Nov 6 16:45:01 2017 -0500

    Remove Doze dialog

    We don't need this, nobody does. Most users are aware of ambient display and
    what is capable of.

    Change-Id: I30abd53cfae1101157b92bf9b869e6469915c2f2

commit 13fdda8179970965a33d1bda2579393149579922
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Mon Nov 6 15:57:56 2017 -0500

    Change package name for uniformity

    With Android O we want to stick to just one package name for device specific doze.

    - Set Doze package to compile
    - Enable bool to hide AOSP ambient display options

    Change-Id: I3279d0d3d06141f282a1135c9fb95f25e2fc994b

commit e0c2473ee1be654a63eea4cc66c566eabcf538c2
Author: Alex Cruz <du.alexcruz@gmail.com>
Date:   Sun May 21 22:51:19 2017 +0200

    Further Refactoring, change theme to match pixel (settings)

    - Remove package from showing up in settings

    - Changed package name so we can do our own thing and not have it
    get in the way of the Doze package currently used by Nick and others

    - Set OneplusDoze to compile

    Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6999ac

commit 272a903f27227f9f2e273fa153fc07dec9e5e0f1
Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
Date:   Sun Aug 21 08:47:12 2016 +0100

    Clean up doze

    * remove always enabled option
    * use stock fade in delay

    Change-Id: Ieebf13f88c02d5036a09b5ef83ca1b53bd6771ac

commit a4c585d09254f326ecb35a9cd4ede87fec09f804
Author: Altaf-Mahdi <altaf.mahdi@gmail.com>
Date:   Sun Apr 24 23:01:57 2016 +0100

    Doze improvements

    * restructure the app
    * add a tilt sensor from hammerhead-caf with an option to enable/disable
    * add a one time dialog on first start to help users understand how the app works
    * remove proximity wake up option and add an option to enable the sensors as soon as the screen turns off
    * adjust and add new doze configs

    Change-Id: Ia9d9a807d6c4f1a80a2ba8780e7486560f9a1d87

commit bedb5d7acde086c01afbc22d3418c8ffd7a74534
Author: Patrick Lower <devvortex@gmail.com>
Date:   Sun May 21 21:47:48 2017 +0200

    Refactoring for the OnePlus 5/5T

    Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f9e9de0f

commit 9c8ccc25db5c64d8b7270e9d752765d55cf3d4da
Author: TheStrix <parthbhatia98@gmail.com>
Date:   Sun May 21 21:35:45 2017 +0200

    Remove summary for Doze

    * Doesn't look good

    Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f8

commit e46da01226d3cbc4cab85d5fd5741388e0cce1c0
Author: Michael Bestas <mikeioannina@gmail.com>
Date:   Tue Dec 1 16:24:07 2015 -0600

    ScreenType util from cmsdk

    Change-Id: I73b610bc71bf07b2fdedb1d5c5931e90f1e6de0f

commit 418fced14cb37edc2b7196534c8499c31073c9f9
Author: Dave Daynard <nardholio@gmail.com>
Date:   Tue Sep 8 22:56:10 2015 -0400

    Fix typo

    Change-Id: Id7716387688080b5ce0a99a4d968e210d8eed6f9

commit dc0a7914655dfaf76bed60b81af03bb73123f0df
Author: Patrick Lower <devvortex@gmail.com>
Date:   Wed Aug 5 10:51:03 2015 -0400

    Properly fix future timestamp error

    Previously attempted fix at review.cyanogenmod.org/#/c/104083/
    The timestamp isn't in the future, that would be impossible.
    The real issue is the timestamp from the SensorEvent is a true
    timestamp, the System.nanoTime is nanoseconds since boot.
    So the previous patch would always return false and never pulse.
    I've simply changed it so that the wakeup call gets sent the current
    System.nanoTime in milliseconds since boot so it does not think the
    event came from the future since the wakeUp method expects
    uptimeMillis, not true world time.

    Change-Id: I78f5e9d61107caf9c3bf6c10fa7c5bb400082294

commit eb876b3d1592a06e9d2f2eefa0cdb6d1ce97a48b
Author: Brandon McAnsh <brandon.mcansh@gmail.com>
Date:   Fri Jul 24 15:40:45 2015 -0400

    Prevent a pm wakeup with a timestamp in the future

    Prevents:

    java.lang.IllegalArgumentException: event time must not be in the future
    at android.os.Parcel.readException(Parcel.java:1550)
            at android.os.Parcel.readException(Parcel.java:1499)
            at android.os.IPowerManager$Stub$Proxy.wakeUp(IPowerManager.java:550)
            at android.os.PowerManager.wakeUp(PowerManager.java:666)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.shouldPulse(SamsungDozeService.java:95)
            at com.cyanogenmod.settings.device.SamsungDozeService$SamsungProximitySensor.onSensorChanged(SamsungDozeService.java:75)
            at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:405)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

    Change-Id: I8ed248271d67216e531b124bf27101fa538f1195
    Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>

commit 6b5ef87592cc024732c9a456aafd32bbfa745658
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat Jul 4 13:44:53 2015 -0400

    Restore proximity wake preference on boot

    Change-Id: I614772d6ff1005968a7f8f1ed0349e3878ddadf1

commit de693ec03b06cb1f6ecae53e6f26ad703ffd6733
Author: Dave Daynard <nardholio@gmail.com>
Date:   Mon May 25 12:54:00 2015 -0400

    Add proximity wake

    Change-Id: Ib02f4611e7b8bc09d540ca5c49aab68ef27f188b

commit cbce9aa1ae4ff743bc45c7198c2d61948ed09c0c
Author: luca020400 <luca.stefani.ge1@gmail.com>
Date:   Sun May 24 15:47:17 2015 -0700

    Add back button to action bar

    Change-Id: Ia56183c8c2d5a6bc25c84f1d1b9823b84bc936c9

commit c0ee7cc43c21957ab3f6e917cd7126590bd4f0b8
Author: Dave Daynard <nardholio@gmail.com>
Date:   Sat May 23 18:29:13 2015 -0400

    Fix defaults

    Change all defaults to false

    Change-Id: I2df507b2fc823d3fb07bce89d44067db565a5ab8

commit 4bcf0849f5f3fa63f9358ad6190b2dea4d9e511a
Author: Christopher R. Palmer <crpalmer@gmail.com>
Date:   Sat May 23 11:42:49 2015 -0700

    Consolidate doze settings

    * Allow user to disable ambient display from gesture panel
    * Disable/enable doze settings based on ambient display state

    Change-Id: I0ff7686ccc04037b3ada9a8355384ba6746cf30c

commit 5724af8b3d59c1252e70dde0380bf03918e3536a
Author: Arne Coucheron <arco68@gmail.com>
Date:   Wed May 20 00:56:19 2015 +0200

    Set gesture to disabled by default

    Change-Id: I0bf3f6a3a4c01bab7ff7522e916e2149f9cfe8d5

commit 2a04e41786070c43472c0d8735cddf3e71ee67cd
Author: Patrick Lower <devvortex@gmail.com>
Date:   Mon May 11 16:14:17 2015 -0400

    Add service for using proximity sensor for wake-up

    * Added custom service that uses proximity sensor in wake-up mode
      to trigger display on
    * If more sensor triggers are suitable to use, they can be added
      to the service

    Change-Id: Id0849fb5c17ff569d771a19cebfc579dc93dbc48

commit 6ad5973a7a824ecada0beaf52c78c3ad6f4f5e09
Author: Alex Cruz <alex@dirtyunicorns.com>
Date:   Sat Sep 15 20:08:20 2018 -0500

    Remove doze package, we'll use the one from o8x

Change-Id: Ia2870584542dc22a3d709cc75201ff0e82ce25c9